[assembly: CrizGames.Vour.OptionalDependency("UnityEngine.XR.XRDisplaySubsystem", "VOUR_XR")]
[assembly: CrizGames.Vour.OptionalDependency("UnityEngine.XR.Management.XRGeneralSettings", "VOUR_XRPLUGINMANAGEMENT")]
[assembly: CrizGames.Vour.OptionalDependency("WebXR.WebXRSubsystem", "VOUR_WEBXR")]
[assembly: CrizGames.Vour.OptionalDependency("WebXRInputProfile.InputProfileLoader", "WEBXR_INPUT_PROFILES")]
[assembly: CrizGames.Vour.OptionalDependency("UnityEngine.XR.Interaction.Toolkit.XRRig", "VOUR_XRI")]
[assembly: CrizGames.Vour.OptionalDependency("UnityEngine.XR.OpenXR.OpenXRRuntime", "VOUR_OPENXR")]
[assembly: CrizGames.Vour.OptionalDependency("Newtonsoft.Json.JsonConvert", "VOUR_JSON")]
